Implement Examples
iCodeNext/DesignPattern pull request #16
Opened 2024-11-27 09:12 UTC by amirhossein33

Implement Examples

2024-11-27 10:39 UTC, mohammadKarimi requested changes

2024-11-27 10:39 UTC, mohammadKarimi commented on Examples/NotificationService.cs
who creates your instance?
can you explain your code?
this class must create a new instance not be just like as a wrapper.

2024-11-27 18:43 UTC, amirhossein33 commented on Examples/NotificationService.cs
In the new code, the class no longer acts as a wrapper and directly creates an instance of the classes and uses them

2024-11-29 07:50 UTC, amirhossein33 commented
@mohammadKarimi  For Code Review

2024-12-05 10:24 UTC, closed without merging